### ISSUE TITLE
En team.js el método getTeamOverallQuality() devuelve un 0

### ISSUE THREAD

**Issue by gabodt16** [imsergiobernal/ec-a3-jest-testing#15]
En el método getTeamOverallQuality() devuelve un 0, pero en los comentarios deja claro que se tiene que calcular igual que el promedio de calidad de un jugador

```javascript
/**
     * Gets the team overall quality. It is calculated as the average of the players' quality
     * @returns {Number} representing the overall quality of the team
     */
    getTeamOverallQuality(){
        return 0;
    }
```

Estuve buscando en player. js como se calcula el promedio y me he dado cuenta que es un valor ya asignado, por lo tanto he ido atrás al json para seguir el trayecto de ese valor para determinar si se modificaba o se utilizaba en algún momento.

El valor inicial del documento json
`"Overall": 94,`

La siguiente vez que es utilizado es en el método estático de player.js: 

```javascript
static fromDatasetJSONObject(playerId,jsonObject){
        let player = new Player(playerId);
        player.id = jsonObject[constants.player_id];
        player.name = jsonObject[constants.name];
        player.country = jsonObject[constants.country];
        player.age = jsonObject[constants.age];
        player.club = jsonObject[constants.club];
        player.overall = jsonObject[constants.overall_quality];
        player.value = jsonObject[constants.market_value];
        let preferredPositions = new Set(jsonObject[constants.preferred_positions].split(' '));
        player._isGoalKeeper = isGoalkeeper(preferredPositions);
        player._isBack = isBack(preferredPositions);
        player._isForward = isForward(preferredPositions);
        player._isMidfielder = isMidfielder(preferredPositions);
        return player;
    }
```
Para ser más exacto aquí: 
`player.overall = jsonObject[constants.overall_quality];`

Y en los métodos de player.js se vuelve a utilizar este valor pero sólo para devolver su contenido, en ningún momento se ve modificado

```javascript
/**
     * Gets the quality of the player
     * @returns {Number} the overall quality of the player
     */
    getQuality(){
        return this.overall;
    }
```

Por lo tanto no se cual sería la correspondiente "fórmula" que tengo que utilizar en el método "getTeamOverallQuality()" para calcular el valor del equipo ya que creo que devolver 0 es un bug.

**Comment by imsergiobernal** [comment]
Eres un crack, efectivamente hay un bug. Yo creo que pondría en el método getTeamOverallQuality() una lógica que itere las qualities de todos los jugadores, haga su media y la retorne. 

Me parece mejor idea que almacenar el valor en una propiedad, por que si un jugador cambia o lo que sea habría que estar actualizando esa propiedad. 

Te atreves?
